#!/usr/bin/env python
from sympy import *
from collections import OrderedDict
import numpy as np
import math
import argparse
import yaml

def setup_yaml():
	""" http://stackoverflow.com/a/8661021 """
	represent_dict_order = lambda self, data:  self.represent_mapping('tag:yaml.org,2002:map', data.items())
	yaml.add_representer(OrderedDict, represent_dict_order)

def planning_8(Ax, Ay, X0, Y0, tf, rate, stop_distance) :
	t = Symbol('t')
	w = Symbol('w')
	phi = Symbol('phi')
	x0 = Symbol('x0')
	y0 = Symbol('y0')

	ax = (2 * Ax) / (3 - cos(2*(w*t + phi)))
	ay = (Ay / 0.35) / (3 - cos(2*(w*t + phi)))

	x = ax*cos(w*t + phi)/2 + x0
	y = ay*sin(2*(w*t + phi))/2 + y0
	dx = diff(x, t)
	dy = diff(y, t)

	_X = lambdify((w, t, phi, x0), x, 'numpy')
	_Y = lambdify((w, t, phi, y0), y, 'numpy')
	_dX = lambdify((w, t, phi, x0), dx, 'numpy')
	_dY = lambdify((w, t, phi, y0), dy, 'numpy')

	T =  1/rate
	t = np.arange(0, tf, T)
	w = 2*math.pi/tf
	phi = math.pi/3

	X = _X(w, t, phi, X0)
	Y = _Y(w, t, phi, Y0)
	dX = _dX(w, t, phi, X0)
	dY = _dY(w, t, phi, Y0)

	positions = np.transpose(np.concatenate(
		(np.expand_dims(X, axis=1), np.expand_dims(Y, axis=1)), 
		axis = 1))
	speeds = np.transpose(np.concatenate(
		(np.expand_dims(dX, axis=1), np.expand_dims(dY, axis=1)), 
		axis = 1))

	np.savetxt('positions.mat', positions, delimiter=" ", fmt="%1.6e")
	np.savetxt('speeds.mat', speeds, delimiter=" ", fmt="%1.6e")

	output = OrderedDict();
	output['Ax'] = Ax 
	output['Ay'] = Ay 
	output['X0'] = X0
	output['Y0'] = Y0
	output['tf'] = tf
	output['rate'] = rate
	output['stop_distance'] = stop_distance
	output['X'] = X.tolist()
	output['Y'] = Y.tolist()
	output['dX'] = dX.tolist()
	output['dY'] = dY.tolist()

	setup_yaml()
	return yaml.dump(output)

def main() :
	parser = argparse.ArgumentParser(description='Generates positions and speeds.')
	parser.add_argument('-d', nargs=2, type=float)
	parser.add_argument('-o', nargs=2, type=float)
	parser.add_argument('-t', type=float)
	parser.add_argument('-r', type=float)
	parser.add_argument('-s', type=float)
	parser.add_argument('-f')

	option = parser.parse_args()
	
	Ax = option.d[0]
	Ay = option.d[1]
	X0 = option.o[0]
	Y0 = option.o[1]
	tf = option.t
	rate = option.r
	stop_distance = option.s
	output = planning_8(Ax, Ay, X0, Y0, tf, rate, stop_distance)
	filename = option.f
	with open(filename + '.yaml', 'w') as output_file :
		output_file.write(output)

if __name__ == "__main__":
    main()
