apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: robot-controller
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: robot-controller
    spec:
      nodeSelector:
        kubernetes.io/hostname: edge
      containers:
      - name: robot-controller-0
        image: git.is:5000/robot-controller:1.1
        command: ["./robot-controller"]
        args: ["-u", "amqp://rabbitmq.kube-system", "-r", "robot.0", "-R", "10.0", "-s", "aruco-tracker.0", "aruco-tracker.1", "aruco-tracker.2", "aruco-tracker.3"]
        imagePullPolicy: Always
        resources:
          limits:
            memory: 256Mi