# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot-parameters.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='robot-parameters.proto',
  package='is.robot',
  syntax='proto3',
  serialized_pb=_b('\n\x16robot-parameters.proto\x12\x08is.robot\"C\n\x05\x46\x65nce\x12\r\n\x05x_min\x18\x01 \x01(\x02\x12\r\n\x05x_max\x18\x02 \x01(\x02\x12\r\n\x05y_min\x18\x03 \x01(\x02\x12\r\n\x05y_max\x18\x04 \x01(\x02\"h\n\nParameters\x12\x15\n\rcenter_offset\x18\x01 \x01(\x02\x12\x14\n\x0cspeed_limits\x18\x02 \x03(\x02\x12\r\n\x05gains\x18\x03 \x03(\x02\x12\x1e\n\x05\x66\x65nce\x18\x04 \x01(\x0b\x32\x0f.is.robot.FenceB\x10\n\x0c\x63om.is.robotP\x01\x62\x06proto3')
)




_FENCE = _descriptor.Descriptor(
  name='Fence',
  full_name='is.robot.Fence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x_min', full_name='is.robot.Fence.x_min', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x_max', full_name='is.robot.Fence.x_max', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_min', full_name='is.robot.Fence.y_min', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y_max', full_name='is.robot.Fence.y_max', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=103,
)


_PARAMETERS = _descriptor.Descriptor(
  name='Parameters',
  full_name='is.robot.Parameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='center_offset', full_name='is.robot.Parameters.center_offset', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed_limits', full_name='is.robot.Parameters.speed_limits', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gains', full_name='is.robot.Parameters.gains', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fence', full_name='is.robot.Parameters.fence', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=209,
)

_PARAMETERS.fields_by_name['fence'].message_type = _FENCE
DESCRIPTOR.message_types_by_name['Fence'] = _FENCE
DESCRIPTOR.message_types_by_name['Parameters'] = _PARAMETERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Fence = _reflection.GeneratedProtocolMessageType('Fence', (_message.Message,), dict(
  DESCRIPTOR = _FENCE,
  __module__ = 'robot_parameters_pb2'
  # @@protoc_insertion_point(class_scope:is.robot.Fence)
  ))
_sym_db.RegisterMessage(Fence)

Parameters = _reflection.GeneratedProtocolMessageType('Parameters', (_message.Message,), dict(
  DESCRIPTOR = _PARAMETERS,
  __module__ = 'robot_parameters_pb2'
  # @@protoc_insertion_point(class_scope:is.robot.Parameters)
  ))
_sym_db.RegisterMessage(Parameters)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\014com.is.robotP\001'))
# @@protoc_insertion_point(module_scope)
