# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: marker.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='marker.proto',
  package='is.vision',
  syntax='proto3',
  serialized_pb=_b('\n\x0cmarker.proto\x12\tis.vision\";\n\x0eMarkerSettings\x12\x12\n\ndictionary\x18\x01 \x01(\x05\x12\x15\n\rmarker_length\x18\x02 \x01(\x02\"Q\n\x12\x43hessboardSettings\x12\x15\n\rsquare_length\x18\x01 \x01(\x02\x12\x11\n\tsquares_x\x18\x02 \x01(\r\x12\x11\n\tsquares_y\x18\x03 \x01(\rB\x11\n\rcom.is.visionP\x01\x62\x06proto3')
)




_MARKERSETTINGS = _descriptor.Descriptor(
  name='MarkerSettings',
  full_name='is.vision.MarkerSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dictionary', full_name='is.vision.MarkerSettings.dictionary', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='marker_length', full_name='is.vision.MarkerSettings.marker_length', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=86,
)


_CHESSBOARDSETTINGS = _descriptor.Descriptor(
  name='ChessboardSettings',
  full_name='is.vision.ChessboardSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='square_length', full_name='is.vision.ChessboardSettings.square_length', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='squares_x', full_name='is.vision.ChessboardSettings.squares_x', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='squares_y', full_name='is.vision.ChessboardSettings.squares_y', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=169,
)

DESCRIPTOR.message_types_by_name['MarkerSettings'] = _MARKERSETTINGS
DESCRIPTOR.message_types_by_name['ChessboardSettings'] = _CHESSBOARDSETTINGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MarkerSettings = _reflection.GeneratedProtocolMessageType('MarkerSettings', (_message.Message,), dict(
  DESCRIPTOR = _MARKERSETTINGS,
  __module__ = 'marker_pb2'
  # @@protoc_insertion_point(class_scope:is.vision.MarkerSettings)
  ))
_sym_db.RegisterMessage(MarkerSettings)

ChessboardSettings = _reflection.GeneratedProtocolMessageType('ChessboardSettings', (_message.Message,), dict(
  DESCRIPTOR = _CHESSBOARDSETTINGS,
  __module__ = 'marker_pb2'
  # @@protoc_insertion_point(class_scope:is.vision.ChessboardSettings)
  ))
_sym_db.RegisterMessage(ChessboardSettings)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\rcom.is.visionP\001'))
# @@protoc_insertion_point(module_scope)
